pipeline:
  identifier: Build_abhishekg2244_TODOUI_1756293690372
  name: Build TODOUI
  orgIdentifier: default
  projectIdentifier: firstharnessproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1756293617652
        repoName: abhishekg2244/TODOUI
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
        description: ""
