pipeline:
  name: deploytonginx
  identifier: deploytonginx
  projectIdentifier: firstharnessproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploytonginx
        identifier: deploytonginx
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          rm -rf /harness/workspace
                          mkdir -p /harness/workspace
                          git clone <your_repo_url> /harness/workspace
                          ls -la /harness/workspace
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          cd /harness/workspace
                          npm ci
                          npm run build
                          mkdir -p /harness/artifacts
                          cp -r build /harness/artifacts/site
                          ls -la /harness/artifacts/site
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_3
                  identifier: ShellScript_3
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          docker exec my-nginx sh -c 'rm -rf /usr/share/nginx/html/*'
                          docker cp /harness/artifacts/site/. my-nginx:/usr/share/nginx/html/
                          echo "Deployment successful!"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
